### ISSUE TITLE
Expected number of kills

### ISSUE THREAD

**Issue by h-2** [SuperMechaCow/supermechacow.github.io#1]
Nice app first of all! [I like that it looks very simple]

It would be great to have not only random dice rolls, but also something like "Expected number of killed models".
I guess if I do "exterminatus the numbers" and divide "Effective damage" by 1000, I get something similar, but an actual expected value would be great! Maybe even with variance?

**Comment by SuperMechaCow** [comment]
This most recent update does now tell you the average of all of the results. After 10000 simulations this is going to be as close to "the expected results" as you could expect from manually calculating the odds, making it effectively the same.

As I think I want to keep this a simulator rather than a calculator, i won't be finishing this feature.

Thank you so much for your feedback!
